# Required variables
title: "Township Small Business Chatbot"
description: "A chatbot to assist small businesses in the township area."

# Optional variables
show_downloads: false
google_analytics: G-PLZZBJYL24




​