[general]
email = "puseletso55@gmail.com"
password = "Daniel@9615"

[mongodb]
uri = "mongodb://atlas-sql-64cf1e5950ebbc37fa7eee8e-icpps.a.query.mongodb.net/ShopLocal-Assistant?ssl=true&authSource=admin"
